### ISSUE TITLE
Leaderboards not using correct pp calculation

### ISSUE THREAD

**Issue by willyosu** [Syriiin/osuchan-backend#2]
I noticed this about a week or go and thought I should report if it persists. My ranking on the leaderboards I've joined is incorrect for most of them. It's fixed by simply leaving and rejoining the leaderboard but at some point it keeps resetting it to the incorrect value on a bunch of them. All the score numbers seem to be accounted for but I guess the weighting seems to be off? No way for me to test for other people so I'm not sure who else this could be affecting.

Username: [Willy](https://osuchan.syrin.me/users/Willy)

**Example 1: [AR8+(HD)DT by Fangzy](https://osuchan.syrin.me/leaderboards/285)**
Incorrect value before:
![image](https://user-images.githubusercontent.com/11691902/79285013-42d40800-7e8a-11ea-83c8-278918ef8693.png)
Correct after rejoining:
![image](https://user-images.githubusercontent.com/11691902/79285060-672fe480-7e8a-11ea-82cc-f5a092bbe04f.png)

**Example 2: [2014 by Syrin](https://osuchan.syrin.me/leaderboards/18)** 
Incorrect value before:
![image](https://user-images.githubusercontent.com/11691902/79285174-c68df480-7e8a-11ea-9c80-e4cbb2bea482.png)
Correct after rejoining:
![image](https://user-images.githubusercontent.com/11691902/79285212-e7564a00-7e8a-11ea-8a07-c8759c24e42a.png)

**Example 3: [(Freemod) AR9 only by verto](https://osuchan.syrin.me/leaderboards/25)** 
Incorrect value before:
![image](https://user-images.githubusercontent.com/11691902/79285271-0e148080-7e8b-11ea-894b-bb5a362734ec.png)
Correct after rejoining:
![image](https://user-images.githubusercontent.com/11691902/79285371-664b8280-7e8b-11ea-9c9d-a63debeed85f.png)

_Note: The last example showed a "Join Leaderboard" button instead of "Leave Leaderboard"
 like the others and after clicking to join my pp count was fixed_

Not sure if this is some caching issue or something, I hope I gave enough information to help out because I really like this project. Cheers!

**Comment by Syriiin** [comment]
Ah interesting.
This must be related to the recent refactor to the leaderboard membership processing system.
I'm guessing that maybe scores are not being correctly sorted before calculating the pp so the wrong scores are being weighted less than others, since that part is slightly different between the initial update when joining a leaderboard as opposed to subsequent updates from profile updates.
Will have to look into this soon.

**Comment by Syriiin** [comment]
Yep it was pretty much what I thought. Simple fix.
Fixed in 59096e03e10ee8c58ca45939ffac71576d45f25d

**Comment by Syriiin** [comment]
I've run a a manual update on all profiles just now so any affected users should be fixed now.
